name: Deploy to Firebase Hosting on merge
on:
    push:
        branches:
            - dev
jobs:
    build_and_deploy:
        name: Build and Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install dependencies and build site
              run: cd source && yarn install && yarn build
            - name: Apply target
              uses: w9jds/firebase-action@master
              with:
                  args: target:apply hosting dev developomp-site
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
