name: Test
on:
    push:
        branches:
            - master
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    deploy:
        if: ${{ github.repository_owner == 'developomp' }}
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Install playwright browsers
              run: npx playwright install --with-deps

            - name: Run tests
              run: pnpm test:e2e

            - uses: actions/upload-artifact@v3
              with:
                  name: playwright-report
                  path: |
                      apps/*/playwright-report
